[font]
size = 16.0

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

# https://github.com/alacritty/alacritty-theme
#[general]
#import = [
#    "~/.config/alacritty/themes/themes/dracula_plus.toml"
#]
